### ISSUE TITLE
Support Creating a Checklist Instance from a Template

### ISSUE THREAD

**Issue by mwi-pharju** [magicwrighter/checklistdojo#16]
Once #4 has been resolved, next we'll want to be able to take a json blob representing a checklist template, and use that to create a new instance of a checklist.

The workflow can go something like this:
1. [ ] On the "templates" page, there should be a list of templates that the user can either run or edit. We can have the app start with a hardcoded list so we have something to work with.
2. [ ] A template should have an "edit" and a "run" button. If a user clicks on "run", it generates a new instance of a checklist based on that template, and routes the user to a page where they can interact with that instance.
3. [ ] Any checklists that have been initiated should be visible on the dashboard.

This workflow will require persisting local app state somewhere. We can either look into integrating our app with redux, or see if there are any new React v16 features that we can use instead.

[ ] Additionally, if the user doesn't have any active checklists, there should be a "start a new checklist" button on the dashboard, which links the user to the "Templates" page.
