### ISSUE TITLE
Persist Checklist Templates By User in a MySql Database

### ISSUE THREAD

**Issue by mwi-pharju** [magicwrighter/checklistdojo#17]
# Summary

As our first step toward persisting information for a given user, we should support persisting Checklist Templates in a MySql Database.

For the sake of simplicity, we can start by storing the template information as json.

We'll need to do the following to consider this issue resolved:
- [ ] Write Migrations for checklist_template_user. Store them in `/dbm`
  - Include a couple example records we can use for priming the database
- [ ] In the Client App, GET the user's template from the DotNet Api when they sign in, or when they view the templates page
- [ ] Add an endpoint to DotNet Api for getting a list of templates by user `GET /api/v1/users/{userId}/templates`
- [ ] In the Client App, POST the template to the DotNet Api when a user saves a new template
- [ ] Add an endpoint to DotNet Api for creating a new template with route `POST /api/v1/users/{userId}/templates`
  - This endpoint should verify that the payload looks valid, store this information in the database, and return the created template instance
- [ ] In the Client App, PATCH the template and title to the DotNet Api when a user updates an existing template
- [ ] Add an endpoint to DotNet Api for creating a new template with route `PATCH /api/v1/users/{userId}/templates/{id}`
  - This endpoint should support updating the title and content of the the checklist template
- [ ] In the Client App, DELETE the template via DotNet Api when a user deletes an existing template
- [ ] Add an endpoint to DotNet Api for creating a new template with route `DELETE /api/v1/users/{userId}/templates/{id}`
  - This endpoint should support updating the title and content of the the checklist template

# Implementation Concerns
## Pull Request Size
I highly recommend only tackling a couple tasks per pull request, to keep things from getting too bloated. For example, the first pull request might include the migrations and the endpoint to get a list of templates.

### checklistdojo.checklist_template_user
|  Field  | Type |
| ------------- | ------------- |
| id  | Content Cell  |
| user_id  | whatever format auth0 recommends (contains letters, so not a long) |
| name | varchar(72) |
| json | textfield |
